### ISSUE TITLE
Input type "tag" should be array

### ISSUE THREAD

**Issue by Bellfalasch** [ItemConsulting/enonic-ts-codegen#30]
When generating types from our XML, any input type using the Enonic type `tag` will generate an interface for a string, but tags are stored as a string only on single values, otherwise it is an array of strings.

What we have:
```
<input name="tags" type="Tag">
     <label>Tags</label>
     <occurrences minimum="0" maximum="0"/>
</input>
```

What we get:

```
  /**
   * Tags
   */
  tags?: string;
```

**Comment by tajakobsen** [comment]
I think we can fix this pretty quickly. 

`string` is the fallback value for types that we havn't supported yet. I can easily add support for it.
